version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    # BAGIAN INI YANG DIGANTI UNTUK TIAP WORKER:
    command: ["node", "src/server.js"]
    network_mode: bridge