version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["node", "src/server.js"]
    # TAMBAHKAN BAGIAN INI:
    ports:
      - "5678:5678"
    network_mode: bridge